name: Typecheck

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    name: Typecheck
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Typecheck
        uses: mrcjkb/lua-typecheck-action@v0.1.2
        with:
          directories: |
            lua
            tests
